version: 1

build:
   os: ubuntu-22.04
   tools:
     python: "3.11"

sphinx:
   configuration: docs/conf.py

formats:
   - pdf

python:
   install:
   - requirements: docs/requirements.txt
   - method: pip
     path: .
