version: 2

build:
   os: ubuntu-22.04
   tools:
     python: "3.11"

sphinx:
   configuration: tetris/docs/conf.py

formats:
   - pdf

python:
   install:
   - requirements: tetris/docs/requirements.txt
   - method: pip
     path: .
